options:
    formatter: stylish
files:
    include: '**/*.s+(a|c)ss'
rules:
    # Extends
    extends-before-mixins: 1
    extends-before-declarations: 1
    placeholder-in-extend: 1

    # Mixins
    mixins-before-declarations: 1

    # Line Spacing
    one-declaration-per-line: 1
    empty-line-between-blocks:
        - 1
        -
            allow-single-line-rulesets: false
    single-line-per-selector: 1

    # Disallows
    no-attribute-selectors: 0
    no-color-hex: 0
    no-color-keywords: 1
    no-color-literals:
        - 1
        -
            allow-rgba: true
    no-combinators: 0
    no-css-comments: 1
    no-debug: 1
    no-disallowed-properties: 0
    no-duplicate-properties: 1
    no-empty-rulesets: 1
    no-extends: 0
    no-ids: 0
    no-important: 0
    no-invalid-hex: 1
    no-mergeable-selectors: 1
    no-misspelled-properties: 1
    no-qualifying-elements:
        - 1
        -
            allow-element-with-class: true
            allow-element-with-attribute: true
    no-trailing-whitespace: 1
    no-trailing-zero: 1
    no-transition-all: 1
    no-universal-selectors: 0
    no-url-protocols: 1
    no-vendor-prefixes:
        - 1
        -
            ignore-non-standard: true
    no-warn: 1
    property-units: 0

    # Nesting
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0

    # Name Formats
    class-name-format:
        - 1
        -
            allow-leading-underscore: false
            convention: 'hyphenatedbem'
    function-name-format:
        - 1
        -
            allow-leading-underscore: false
    id-name-format:
        - 1
        -
            allow-leading-underscore: false
    mixin-name-format:
        - 1
        -
            allow-leading-underscore: false
    placeholder-name-format:
        - 1
        -
            allow-leading-underscore: false
    variable-name-format:
        - 1
        -
            allow-leading-underscore: false

    # Style Guide
    attribute-quotes: 1
    bem-depth: 1
    border-zero: 1
    brace-style:
        - 1
        -
            allow-single-line: false
    clean-import-paths: 1
    empty-args: 1
    hex-length: 1
    hex-notation: 1
    indentation:
        - 1
        -
            size: 4
    leading-zero: 0
    nesting-depth:
        - 1
        -
            max-depth: 3
    property-sort-order:
        - 1
        -
            order:
                - position
                - top
                - right
                - bottom
                - left
                - z-index
                - display
                - visibility
                - flex-direction
                - flex-order
                - flex-pack
                - float
                - clear
                - flex-align
                - flex
                - overflow
                - overflow-x
                - overflow-y
                - clip
                - box-sizing
                - margin
                - margin-top
                - margin-right
                - margin-bottom
                - margin-left
                - padding
                - padding-top
                - padding-right
                - padding-bottom
                - padding-left
                - min-width
                - min-height
                - max-width
                - max-height
                - width
                - height
                - perspective
                - perspective-origin
                - outline
                - outline-width
                - outline-style
                - outline-color
                - outline-offset
                - border
                - border-spacing
                - border-collapse
                - border-width
                - border-style
                - border-color
                - border-top
                - border-top-width
                - border-top-style
                - border-top-color
                - border-right
                - border-right-width
                - border-right-style
                - border-right-color
                - border-bottom
                - border-bottom-width
                - border-bottom-style
                - border-bottom-color
                - border-left
                - border-left-width
                - border-left-style
                - border-left-color
                - border-radius
                - border-top-left-radius
                - border-top-right-radius
                - border-bottom-right-radius
                - border-bottom-left-radius
                - border-image
                - border-image-source
                - border-image-slice
                - border-image-width
                - border-image-outset
                - border-image-repeat
                - border-top-image
                - border-right-image
                - border-bottom-image
                - border-left-image
                - border-corner-image
                - border-top-left-image
                - border-top-right-image
                - border-bottom-right-image
                - border-bottom-left-image
                - background
                - filter:progid:DXImageTransform.Microsoft.AlphaImageLoader
                - background-color
                - background-image
                - background-attachment
                - background-position
                - background-position-x
                - background-position-y
                - background-clip
                - background-origin
                - background-size
                - background-repeat
                - box-decoration-break
                - box-shadow
                - color
                - table-layout
                - caption-side
                - empty-cells
                - list-style
                - list-style-position
                - list-style-type
                - list-style-image
                - quotes
                - content
                - counter-increment
                - counter-reset
                - vertical-align
                - text-align
                - text-align-last
                - text-decoration
                - text-emphasis
                - text-emphasis-position
                - text-emphasis-style
                - text-emphasis-color
                - text-indent
                - text-justify
                - text-outline
                - text-transform
                - text-wrap
                - text-overflow
                - text-overflow-ellipsis
                - text-overflow-mode
                - text-shadow
                - white-space
                - word-spacing
                - word-wrap
                - word-break
                - tab-size
                - hyphens
                - letter-spacing
                - font
                - font-weight
                - font-style
                - font-variant
                - font-size-adjust
                - font-stretch
                - font-size
                - font-family
                - src
                - line-height
                - opacity
                - filter:progid:DXImageTransform.Microsoft.Alpha(Opacity
                - filter
                - resize
                - cursor
                - nav-index
                - nav-up
                - nav-right
                - nav-down
                - nav-left
                - transition
                - transition-delay
                - transition-timing-function
                - transition-duration
                - transition-property
                - backface-visibility
                - transform
                - transform-style
                - transform-origin
                - animation
                - animation-name
                - animation-duration
                - animation-play-state
                - animation-timing-function
                - animation-delay
                - animation-iteration-count
                - animation-direction
                - pointer-events
                - unicode-bidi
                - direction
                - columns
                - column-span
                - column-width
                - column-count
                - column-fill
                - column-gap
                - column-rule
                - column-rule-width
                - column-rule-style
                - column-rule-color
                - break-before
                - break-inside
                - break-after
                - page-break-before
                - page-break-inside
                - page-break-after
                - orphans
                - widows
                - zoom
                - max-zoom
                - min-zoom
                - user-zoom
                - orientation
    pseudo-element: 1
    quotes: 1
    shorthand-values: 1
    url-quotes: 1
    variable-for-property: 1
    zero-unit: 1

    # Inner Spacing
    space-after-comma: 1
    space-before-colon: 1
    space-after-colon: 1
    space-before-brace: 1
    space-before-bang: 1
    space-after-bang: 1
    space-between-parens: 1
    space-around-operator: 1

    # Final Items
    trailing-semicolon: 1
    final-newline: 1
